### ISSUE TITLE
hummingbird gives errors during amo87215

### ISSUE THREAD

**Issue by FilipeMaia** [SPIhub/hummingbird#59]
We can't exactly reproduce but the error is the following:

```python
Traceback (most recent call last):
  File "/reg/neh/operator/amoopr/amo87215/hummingbird/src/interface/data_source.py", line 167, in _get_broadcast
    self._process_broadcast(data)
  File "/reg/neh/operator/amoopr/amo87215/hummingbird/src/interface/data_source.py", line 188, in _process_broadcast
    self._plotdata[title].append(data, data_x, '')
  File "/reg/neh/operator/amoopr/amo87215/hummingbird/src/interface/plotdata.py", line 36, in append
    self._l.append(l)
  File "/reg/neh/operator/amoopr/amo87215/hummingbird/src/interface/ringbuffer.py", line 161, in append
    self._init_data()
  File "/reg/neh/operator/amoopr/amo87215/hummingbird/src/interface/ringbuffer.py", line 181, in _init_data
    self._data = [None for i in xrange(self._maxlen)]
TypeError: integer argument expected, got float
```

**Comment by daurer** [comment]
#72
