### ISSUE TITLE
Error during replot

### ISSUE THREAD

**Issue by FilipeMaia** [SPIhub/hummingbird#62]
```python
Traceback (most recent call last):
  File "/reg/neh/operator/amoopr/amo87215/hummingbird/src/interface/gui.py", line 209, in _replot
    p.replot()
  File "/reg/neh/operator/amoopr/amo87215/hummingbird/src/interface/ui/plot_window.py", line 276, in replot
    y,x = numpy.histogram(y, range=(hmin, hmax), bins=bins)
  File "/reg/neh/home/benedikt/.local/lib/python2.7/site-packages/numpy/lib/function_base.py", line 176, in histogram
    'max must be larger than min in range parameter.')
AttributeError: max must be larger than min in range parameter.
```

**Comment by daurer** [comment]
#72
